#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

ENGINE_ROOT = File.expand_path('../..', __coolgames__)
ENGINE_PATH = File.expand_path('../../lib/cool_games/engine', __coolgames__)

require 'rails/all'
require 'rails/engine/commands'
